
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cpp-5 
    - libsdl2-dev
    - libsdl2-image-dev
    
before_install:
  - apt-cache search libsdl2

script:
    - echo hello
