language: elixir

elixir:
  - 1.2.0
otp_release:
  - 18.0

matrix:
  include:
    - os: linux
      sudo: false
    - os: linux
      sudo: required
    - os: linux
      sudo: required
      dist: trusty

before install:
  - nvm install 5.7.1
  - nvm use 5.7.1

script: echo hello