language: generic
sudo: false

env:
  - BUILD_ENV=staging
  - BUILD_ENV=develop

script:
  - travis wait fail this build

deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  on:
    all_branches: true
    condition: '"$BUILD_ENV" = "develop"'
