sudo: false
addons:
  apt:
    sources:
    - ubuntu-sdk-team
    packages:
    - libqt5webkit5-dev
    - qtdeclarative5-dev

script:
    - echo hello
    - gcc --version
    - g++ --version
    - qmake -v
