sudo: false
language: android

jdk: oraclejdk8

android:
  components:
    - build-tools-23.0.1
    - build-tools-22.0.1
    - android-23
    - android-22
    - extra
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23
    - addon-google_apis-google-22

script: echo "hola"