language: java

sudo: false

addons:
  apt:
    sources:
      - debian-sid
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - python2.7
      - wget
      - pkg-config
      - zip
      - zlib1g-dev

before_install:
    - which gcc
    - gcc --version
    - which gcc-4.8
    - gcc-4.8 --version

install:
      - which $CXX
      - which $CC
      - $CXX --version

script: echo hola
