language: generic
matrix:
  include:
    - env: AG_VER=master
      os: linux
      sudo: false
      addons:
        apt:
          packages:
            - pkg-config
            - libpcre3-dev
            - zlib1g-dev
      install: true
      script: echo hola
    - env: AG_VER=0.31.0
      os: linux
      sudo: false
      addons:
        apt:
          packages:
            - pkg-config
            - libpcre3-dev
            - zlib1g-dev
      install: true
      script: echo hola
