
sudo: false
language: c++

matrix:
  include:
    # Test clang-3.4: C++11
    - env: CLANG_VERSION=3.4 CPP=11 LIBCXX=On
      os: linux
      compiler: clang34
      addons: &clang34
        apt:
          sources:
            - ubuntu-toolchain-r-test

    # Test clang-3.7:  C++11
    - env: CLANG_VERSION=3.7 CPP=11 LIBCXX=On
      os: linux
      addons: &clang37
        apt:
          packages:
            - clang-3.7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise

    # Test clang-3.7:  C++14
    - env: CLANG_VERSION=3.7 CPP=14 LIBCXX=On
      os: linux
      addons: *clang37

    # Test gcc-5.0: C++11
    - env: GCC_VERSION=5 CPP=11 LIBCXX=Off
      os: linux
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test

    # Test gcc-5.0: C++14
    - env: GCC_VERSION=5 CPP=14 LIBCXX=Off
      os: linux
      addons: *gcc5