sudo: required
addons:
  apt:
    sources:
    - ubuntu-sdk-team
    packages:
    - qt5-default
    - qttools5-dev-tools

script:
    - echo hello
    - gcc --version
    - g++ --version
    - qmake -v
